# Generated by Django 6.0.2 on 2026-03-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_task_sharepoint_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attached_image',
            field=models.ImageField(blank=True, null=True, upload_to='task_images/'),
        ),
    ]
